### ISSUE TITLE
tests not running with R16B03, lubuntu 32bit

### ISSUE THREAD

**Issue by exterm** [ferd/howistart-erlang1-code#2]
Hi there,

First of all thanks for the great tutorial (and `LYSE` of course)!
I can't get the tests to run on my machine. For some reason, mocking `io` does not seem to work:

    ct_util_server got EXIT from <0.43.0: {{not_mocked,io},                                                                     
                                        [{meck_proc,gen_server,3,                                                            
                                          [{file,"src/meck_proc.erl"},                                                       
                                           {line,437}]},                                                                     
                                         {meck_code_gen,exec,4,                                                              
                                          [{file,"src/meck_code_gen.erl"},                                                   
                                           {line,147}]},                                                                     
                                         {ct_logs,print_to_log,6,                                                            
                                          [{file,"ct_logs.erl"},{line,831}]},                                                
                                         {ct_logs,logger_loop,1,                                                             
                                          [{file,"ct_logs.erl"},{line,716}]}]}

I have an up to date lubuntu 32bit installation with erlang R16B03.

**Comment by exterm** [comment]
I just checked, doesn't work with R17 either.

**Comment by ferd** [comment]
Can you try replacing these two lines: https://github.com/ferd/howistart-erlang1-code/blob/master/tests/apps/muumuu/test/muumuu_SUITE.erl#L36-L37

by:

`meck:new(io, [passthrough, no_link, unstick]),`

and see if it works? It's a bit weird that it fails given I've built and tested it on R16B03-1 for the blog post.

**Comment by exterm** [comment]
Hey, thanks for your answer. I already tried that and it failed too, sorry :-(

**Comment by ferd** [comment]
Well I don't think I can easily figure it out. It works for me:

```
λ tests : master → export PATH=/Users/ferd/.kerl/builds/r16b03-1/release_R16B03-1/bin:/Users/ferd/bin:$PATH
λ tests → master → ./rebar get-deps compile
WARN:  Expected /Users/ferd/code/self/howistart-erlang1-code/tests/deps/meck to be an app dir (containing ebin/*.app), but no .app found.
==> muumuu (get-deps)
==> tests (get-deps)
WARN:  Expected /Users/ferd/code/self/howistart-erlang1-code/tests/deps/meck to be an app dir (containing ebin/*.app), but no .app found.
Pulling meck from {git,"https://github.com/eproxus/meck.git",{tag,"0.8.1"}}
Cloning into 'meck'...
==> meck (get-deps)
==> meck (get-deps)
==> muumuu (get-deps)
==> tests (get-deps)
==> meck (compile)
Compiled src/meck_matcher.erl
Compiled src/meck_history.erl
Compiled src/meck_proc.erl
Compiled src/meck_cover.erl
Compiled src/meck_expect.erl
Compiled src/meck_args_matcher.erl
Compiled src/meck_code.erl
Compiled src/meck_code_gen.erl
Compiled src/meck.erl
==> muumuu (compile)
Compiled src/muumuu_app.erl
Compiled src/muumuu_sup.erl
Compiled src/muumuu_fsm.erl
==> tests (compile)
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /Users/ferd/code/self/howistart-erlang1-code/tests/apps
          /Users/ferd/code/self/howistart-erlang1-code/tests/deps
          /Users/ferd/.kerl/builds/R16B03-1/release_R16B03-1/lib
===> Resolving available OTP Releases from directories:
          /Users/ferd/code/self/howistart-erlang1-code/tests/apps
          /Users/ferd/code/self/howistart-erlang1-code/tests/deps
          /Users/ferd/.kerl/builds/R16B03-1/release_R16B03-1/lib
===> Resolved muumuu-1.0.0
===> release successfully created!
λ tests → master → rebar ct -r skip_deps=true
==> muumuu (ct)
DONE.
Testing apps.muumuu: TEST COMPLETE, 1 ok, 0 failed of 1 test cases

WARN:  'ct' command does not apply to directory /Users/ferd/code/self/howistart-erlang1-code/tests
```

Not sure why your end of the deal is failing there.

**Comment by exterm** [comment]
Just tried again with R17. Had to bump the meck version to 0.8.2 but it works now. Should I create a pull request?

**Comment by exterm** [comment]
Created a PR https://github.com/ferd/howistart-erlang1-code/pull/3
